### ISSUE TITLE
compilation error !

### ISSUE THREAD

**Issue by lilux618** [alibaba/libgrape-lite#107]
**Do you have questions or need support? Please describe.**
I downloaded the source code from github, after running the make -j command, the program has the following error, I want to know what's going on?
<img width="767" alt="屏幕截图 2022-05-07 171314" src="https://user-images.githubusercontent.com/60692776/167247756-8c079d3e-6f4d-4daf-9f45-0296a86293e0.png">

**Additional context**
Add any other context about the question here.

**Comment by sighingnow** [comment]
You need

```
git submodule init --recursive
```

Before building the GPU support.
