### ISSUE TITLE
[BUG]Compilation error

### ISSUE THREAD

**Issue by lilux618** [alibaba/libgrape-lite#109]
**Describe the bug**
I run “make” then got error ! 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/60692776/168220647-dbb27973-a1d4-47e0-b2a3-7c278284bffa.png">

<img width="548" alt="屏幕截图 2022-05-13 135421" src="https://user-images.githubusercontent.com/60692776/168220412-3585c76b-dc17-4052-a8aa-023e3bfeca77.png">
 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/60692776/168220647-dbb27973-a1d4-47e0-b2a3-7c278284bffa.png">

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Operation System version (`uname -a`): Linux eff814a706ff 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
2. The version of libgrape-lite you use:  latest
3. Versions of crucial packages, such as mpi: mpirun (Open MPI) 4.1.2
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Expected behavior**

**Additional context**

**Comment by septicmk** [comment]
Should be fixed by #110.
