### ISSUE TITLE
The benchmark data set link is not valid!

### ISSUE THREAD

**Issue by lilux618** [alibaba/libgrape-lite#111]
I want to reproduce the result in Performance.md, but the datasets in website link https://graphalytics.org/datasets offered in Performance.md can't be download . I want to get some datasets like graph500-22 or others . Where can I get them?

**Comment by yecol** [comment]
Hi @lilux618 
The datasets marked as TBA are officially not released.

**Comment by septicmk** [comment]
Hi, @lilux618, you can download datasets from https://ldbcouncil.org/benchmarks/graphalytics/

**Comment by sighingnow** [comment]
Close as fixed by #112.
