### ISSUE TITLE
Add Dockerfile or docker image

### ISSUE THREAD

**Issue by WanXiaopei** [alibaba/libgrape-lite#158]
It is difficult to compile the codes successfully without Dockerfile or docker image, such as incompatible version of gflags, glog and nccl, so, can you provide it?

**Comment by lidongze0629** [comment]
@WanXiaopei 

You can compile libgrape-lite in image ` registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:v0.16.4`

**Comment by sighingnow** [comment]
Closing as resolved.
