### ISSUE TITLE
[BUG] Wrong number of vertices when the vertex does not appear in the edge file

### ISSUE THREAD

**Issue by pwrliang** [alibaba/libgrape-lite#31]
**Describe the bug**

When the VDATA_T is grape::EmptyType, the vertex will not be added to GlobalVertexMap.

**To Reproduce**
example.e

```
0 1
3 1
```

example.v
```
0
1
2
3
```

```cpp
auto inner_vertices = frag.InnerVertices();

LOG(INFO) << "|V|: " << inner_vertices.size();
// THE OUTPUT IS
// I1225 19:43:47.534154 288427520 pagerank.h:59] |V|: 3
```

**Expected behavior**
The output should be 4 instead of 3.

**Additional context**
Note: Fix the bug may increase the memory usage since all the vertices have to be added for every worker. Before the fix, we only need to add vertices that cross the fragment.

**Comment by sighingnow** [comment]
The value returned by `inner_vertices.size()` don't means the "vertex size" and the data structure `inner_vertices` is only used for iteration in algorithms.

To get the count of vertices in the graph, please refer to `frag.GetTotalVerticesNum()` (https://github.com/alibaba/libgrape-lite/blob/master/grape/fragment/fragment_base.h#L134).

Close as answered.
