### ISSUE TITLE
[BUG] Segmentation fault when VDATA_T == std::string and the length of input vertex label is larger than 22

### ISSUE THREAD

**Issue by samjjx** [alibaba/libgrape-lite#37]
**Describe the bug**
Segmentation fault when VDATA_T == std::string and the length of input vertex label is larger than 22. 

**To Reproduce**
To reproduce the bug, you may 
1) set VDATA_T to std::string at run.h:173:
`using GraphType = ImmutableEdgecutFragment<OID_T, VID_T, std::string, double>;`
2) and change the first line of ./dataset/p2p-31.v from *1 7* to *1 7777777777777777777777*

**Expected behavior**
The graph should be loaded successfully.

**Additional context**

This problem is caused at ev_fragment_loader.h:181: 
`basic_fragment_loader_.ConstructFragment(fragment);`

**Comment by pwrliang** [comment]
Hi samjjx, libgrape-lite does not support a graph that the data type of vertex/edge is string or other complex types.

**Comment by luoxiaojian** [comment]
Hi @samjjx , this is fixed in #38 .

**Comment by samjjx** [comment]
@luoxiaojian hi, xiaojian, thanks for your update!
