### ISSUE TITLE
[BUG] cmake failed to generate Makefile without librdkafka 

### ISSUE THREAD

**Issue by wenyuanyu** [alibaba/libgrape-lite#5]
**Describe the bug**
Building examples should be optional when dependencies are not met.

👍 Without gflags, the build can still proceed without producing examples as targets.
👎 But when librdkafka is not installed, cmake fails without producing a Makefile.

**To Reproduce**
try ``cmake ..`` without librdkafka installed.

**Expected behavior**
1. an option should be added to CMakeLists for users to configure if examples targets shall be generated
2. turn off the option if any of examples' dependencies were not met, and still produce the Makefile without examples

**Comment by wenyuanyu** [comment]
will fix along #3

**Comment by sighingnow** [comment]
Check if `librdkafka` exists is tricky, because librdkafka is found by cppkafka using a customized CMake module, and we have no "try-catch" build block for `add_subdirectory` in `CMakeLists.txt`.

PR #6 will fix this issue.
